/*
 * JSP generated by Resin-4.0.67 (built Thu, 01 Aug 2024 10:12:42 PDT)
 */

package _jsp._sysop;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public class _post_0edit__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    

Malgn m = new Malgn(request, response, out);

Form f = new Form();
f.setRequest(request);

Page p = new Page();
p.setRequest(request, response);
p.setWriter(out);

int userId = 0;
String userName = "";
String userType = "";
String userLogin = "";
String userBirthday = "";
boolean isAdult = false;
int sellerStatus = 0;

Auth auth = new Auth(request, response); 
auth.keyName = "AUTHID1867";

// ISO 8601 \ud615\uc2dd \ub0a0\uc9dc \ubcc0\ud658
SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy.MM.dd");

if(auth.isValid()) {
    userId = auth.getInt("id");
	userName = auth.getString("name");
	userLogin = auth.getString("uid");
	userBirthday = auth.getString("birthday");
	p.setVar("login_block", true);
} else {
	p.setVar("login_block", false);
}

    

UserDao userDao = new UserDao();
auth.loginURL = "/sysop/login/login.jsp";

if(userId == 0) auth.loginForm();

DataSet user = userDao.find("id = " + userId + " AND role = 1");

p.setVar("user", user);

    

// DAO \uac1d\uccb4 \uc0dd\uc131
PostDao postDao = new PostDao();

// \ud30c\ub77c\ubbf8\ud130 \ubc1b\uae30 (\uc218\uc815\ud560 \uac8c\uc2dc\ubb3c ID)
int id = m.ri("id");
if (id == 0) {
    m.jsError("\uc798\ubabb\ub41c \uc811\uadfc\uc785\ub2c8\ub2e4. \uac8c\uc2dc\ubb3c ID\uac00 \ud544\uc694\ud569\ub2c8\ub2e4.");
    return;
}

// \uac8c\uc2dc\ubb3c \uc815\ubcf4 \uc870\ud68c (\uc218\uc815\ud560 \ub0b4\uc6a9 \ub85c\ub4dc)
DataSet post = postDao.find("id = " + id + " AND status != -1"); // \uc0ad\uc81c\ub418\uc9c0 \uc54a\uc740 \uac8c\uc2dc\ubb3c\ub9cc
if (!post.next()) {
    m.jsError("\uac8c\uc2dc\ubb3c\uc744 \ucc3e\uc744 \uc218 \uc5c6\uac70\ub098 \uc0ad\uc81c\ub418\uc5c8\uc2b5\ub2c8\ub2e4.");
    return;
}

// \ud3fc \uac1d\uccb4 \ucd08\uae30\ud654 (\uc218\uc815)
f.addElement("title", post.s("title"), "required:'Y'"); // \uae30\uc874 \uac12\uc73c\ub85c \ucd08\uae30\ud654
f.addElement("content", post.s("content"), "required:'Y'"); // \uae30\uc874 \uac12\uc73c\ub85c \ucd08\uae30\ud654

// POST \uc694\uccad \ucc98\ub9ac (\uac8c\uc2dc\ubb3c \uc218\uc815)
if (m.isPost() && f.validate()) {
    
    // \ub370\uc774\ud130 \uc900\ube44
    String title = f.get("title");
    String content = f.get("content");
    // updated_at\uc740 DB\uc5d0\uc11c \uc790\ub3d9\uc73c\ub85c \uc5c5\ub370\uc774\ud2b8\ub418\ub3c4\ub85d \uc124\uc815\ub418\uc5b4 \uc788\uc5b4\uc57c \ud568

    postDao.item("title", title);
    postDao.item("content", content);
    postDao.item("updated_at", m.time("yyyyMMddHHmmss"));
    // \ub370\uc774\ud130\ubca0\uc774\uc2a4 \uc5c5\ub370\uc774\ud2b8
    if (!postDao.update("id = " + id)) {
        m.jsAlert("\uac8c\uc2dc\ubb3c\uc744 \uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4.");
        // \uc2e4\ud328 \uc2dc \ud604\uc7ac \ud398\uc774\uc9c0\uc5d0 \uba38\ubb34\ub974\uac70\ub098 \ub2e4\ub978 \ucc98\ub9ac \uac00\ub2a5
    } else {
        // \uc131\uacf5 \uc2dc \uac8c\uc2dc\ubb3c \ubcf4\uae30 \ud398\uc774\uc9c0\ub85c \uc774\ub3d9
        m.jsAlert("\uac8c\uc2dc\ubb3c\uc774 \uc131\uacf5\uc801\uc73c\ub85c \uc218\uc815\ub418\uc5c8\uc2b5\ub2c8\ub2e4.");
        m.jsReplace("post_view.jsp?id=" + id);
        return; // \ub9ac\ub2e4\uc774\ub809\uc158 \ud6c4 \ucf54\ub4dc \uc2e4\ud589 \uc911\uc9c0
    }
}

// GET \uc694\uccad \ub610\ub294 POST \uc2e4\ud328 \uc2dc (\ud3fc \ucd9c\ub825)
p.setLayout("sysop");
p.setBody("sysop.post_edit");
p.setVar("post", post); // \uc870\ud68c\ub41c \uac8c\uc2dc\ubb3c \uc815\ubcf4\ub97c \ud15c\ud50c\ub9bf\uc5d0 \uc804\ub2ec
p.setVar("form_script", f.getScript());
p.display();


    out.write(' ');
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5413665724253103304L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/post_edit.jsp"), -8267987571360552682L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), 7271381338628451703L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("init.jsp"), 8583015042390199441L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
}
