/*
 * JSP generated by Resin-4.0.67 (built Thu, 01 Aug 2024 10:12:42 PDT)
 */

package _jsp._sysop;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public class _user_0add__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    

Malgn m = new Malgn(request, response, out);

Form f = new Form();
f.setRequest(request);

Page p = new Page();
p.setRequest(request, response);
p.setWriter(out);

int userId = 0;
String userName = "";
String userType = "";
String userLogin = "";
String userBirthday = "";
boolean isAdult = false;
int sellerStatus = 0;

Auth auth = new Auth(request, response); 
auth.keyName = "AUTHID1867";

// ISO 8601 \ud615\uc2dd \ub0a0\uc9dc \ubcc0\ud658
SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy.MM.dd");

if(auth.isValid()) {
    userId = auth.getInt("id");
	userName = auth.getString("name");
	userLogin = auth.getString("uid");
	userBirthday = auth.getString("birthday");
	p.setVar("login_block", true);
} else {
	p.setVar("login_block", false);
}

    

UserDao userDao = new UserDao();
auth.loginURL = "/sysop/login/login.jsp";

if(userId == 0) auth.loginForm();

DataSet user = userDao.find("id = " + userId + " AND role = 1");

p.setVar("user", user);

    

UserDao user2 = new UserDao();

if("CHECK".equals(m.rs("mode"))) {
	String value = m.rs("v");
	if("".equals(value)) { return; }

	//\uc911\ubcf5\uc5ec\ubd80
	if(0 < user2.findCount("username = '" + value + "'")) {
		out.print("<span class='bad'>\uc0ac\uc6a9 \uc911\uc778 \ub85c\uadf8\uc778\uc544\uc774\ub514\uc785\ub2c8\ub2e4. \ub2e4\uc2dc \uc785\ub825\ud574 \uc8fc\uc138\uc694.</span>");
	} else {
		out.print("<span class='good'>\uc0ac\uc6a9\ud560 \uc218 \uc788\ub294 \ub85c\uadf8\uc778\uc544\uc774\ub514\uc785\ub2c8\ub2e4.</span>");
	}
	return;
}

f.addElement("name", null, "required:'Y'");
f.addElement("username", null, "required:'Y'");
f.addElement("password", null, "required:'Y'");
f.addElement("role", null, "required:'Y'");
f.addElement("status", null, "required:'Y'");
f.addElement("email", null, "");
f.addElement("phone", null, "");

if(m.isPost() && f.validate()) {
    //\uc81c\ud55c
	if(0 < user2.findCount("username = '" + f.get("username") + "'")) { m.jsAlert("\uc0ac\uc6a9 \uc911\uc778 \ub85c\uadf8\uc778\uc544\uc774\ub514\uc785\ub2c8\ub2e4. \ub2e4\uc2dc \uc785\ub825\ud558\uc138\uc694."); return; }
	if(0 < user2.findCount("email = '" + f.get("email") + "'")) {
		m.jsAlert("\ud574\ub2f9 \uc774\uba54\uc77c( " + f.get("email") + " )\uc744 \uc0ac\uc6a9\uc911\uc785\ub2c8\ub2e4. \ub2e4\uc2dc \uc785\ub825\ud558\uc138\uc694.");
		m.jsReplace("check_bc.jsp?" + m.qs(), "parent");
		return;
	}

    userDao.item("name", f.get("name"));
    userDao.item("username", f.get("username"));
	userDao.item("password", m.encrypt(f.get("password"), "SHA-256"));
    userDao.item("role", f.get("role"));
    userDao.item("email", f.get("email"));
    userDao.item("phone", f.get("phone"));
    userDao.item("status", f.get("status"));
    userDao.item("created_at", m.time("yyyyMMddHHmmss"));

    if (!userDao.insert()){
        m.jsError("error");
        return;
    }
    m.redirect("/sysop/user_list.jsp");
    return;
}

p.setLayout("sysop");
p.setBody("sysop.user_add");
p.setVar("form_script", f.getScript());
p.display();


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5413665724253103304L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/user_add.jsp"), -3077335166654115884L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), 7271381338628451703L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("init.jsp"), 8583015042390199441L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
}
